/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Mon Mar 09 22:54:07 2026 */

/* parameterized module instance */
lattice_pll __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ));
