/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Thu Feb 26 22:44:25 2026 */

/* parameterized module instance */
lattice_pll __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ));
