/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.8 */
/* Sun Feb 22 22:43:08 2026 */

/* parameterized module instance */
aes50_rmii_txd __ (.clkout( ), .refclk( ), .reset( ), .data( ), .dout( ));
