/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.8 */
/* Sun Jan 04 23:35:24 2026 */

/* parameterized module instance */
aes50_clk_ddr __ (.clkout( ), .refclk( ), .reset( ), .data( ), .dout( ));
