/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.8 */
/* C:\Programme2\Lattice\Diamond\ispfpga\bin\nt64\scuba.exe -w -n aes50_clk_ddr -lang verilog -synth synplify -bus_exp 7 -bb -arch sa5p00 -type iol -mode Transmit -io_type LVCMOS33 -width 1 -freq_in 50.00 -gear 2 -aligned -del -1 -fdc O:/fpga/lattice/claritydesigner/aes50_clk_ddr/aes50_clk_ddr.fdc  */
/* Mon Feb 23 11:09:24 2026 */


`timescale 1 ns / 1 ps
module aes50_clk_ddr (clkout, refclk, reset, data, dout)/* synthesis NGD_DRC_MASK=1 */;
    input wire refclk;
    input wire reset;
    input wire [1:0] data;
    output wire clkout;
    output wire [0:0] dout;

    wire db0;
    wire da0;
    wire scuba_vlo;
    wire scuba_vhi;
    wire sclk_t;
    wire clkos;
    wire clkop;
    wire buf_clkout;
    wire buf_douto0;

    ODDRX1F Inst4_ODDRX1F0 (.SCLK(sclk_t), .RST(reset), .D0(da0), .D1(db0), 
        .Q(buf_douto0));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    ODDRX1F Inst3_ODDRX1F (.SCLK(clkos), .RST(reset), .D0(scuba_vhi), .D1(scuba_vlo), 
        .Q(buf_clkout));

    OB Inst2_OB (.I(buf_clkout), .O(clkout))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB0 (.I(buf_douto0), .O(dout[0]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    assign db0 = data[1];
    assign da0 = data[0];
    assign sclk_t = clkop;
    assign clkos = refclk;
    assign clkop = refclk;


    // exemplar begin
    // exemplar attribute Inst2_OB IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB0 IO_TYPE LVCMOS33
    // exemplar end

endmodule
