/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.8 */
/* Mon Feb 23 11:09:24 2026 */

/* parameterized module instance */
aes50_clk_ddr __ (.clkout( ), .refclk( ), .reset( ), .data( ), .dout( ));
