/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.8 */
/* C:\Programme2\Lattice\Diamond\ispfpga\bin\nt64\scuba.exe -w -n aes50_rmii_rxd -lang verilog -synth synplify -bus_exp 7 -bb -arch sa5p00 -type iol -mode Receive -io_type LVCMOS33 -width 3 -freq_in 50 -del -1 -gear 1 -fdc O:/fpga/lattice/claritydesigner/aes50_rmii_rxd/aes50_rmii_rxd.fdc  */
/* Wed Feb 25 23:53:50 2026 */


`timescale 1 ns / 1 ps
module aes50_rmii_rxd (clkin, reset, sclk, datain, q)/* synthesis NGD_DRC_MASK=1 */;
    input wire clkin;
    input wire reset;
    input wire [2:0] datain;
    output wire sclk;
    output wire [2:0] q;

    wire buf_clkin_inv;
    wire scuba_vhi;
    wire dataini_t2;
    wire dataini_t1;
    wire dataini_t0;
    wire buf_dataini2;
    wire buf_dataini1;
    wire buf_dataini0;

    INV INV_0 (.A(clkin), .Z(buf_clkin_inv));

    IFS1P3DX Inst2_IFS1P3DX2 (.D(dataini_t2), .SP(scuba_vhi), .SCLK(buf_clkin_inv), 
        .CD(reset), .Q(q[2]));

    IFS1P3DX Inst2_IFS1P3DX1 (.D(dataini_t1), .SP(scuba_vhi), .SCLK(buf_clkin_inv), 
        .CD(reset), .Q(q[1]));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    IFS1P3DX Inst2_IFS1P3DX0 (.D(dataini_t0), .SP(scuba_vhi), .SCLK(buf_clkin_inv), 
        .CD(reset), .Q(q[0]));

    IB Inst1_IB2 (.I(datain[2]), .O(buf_dataini2))
             /* synthesis IO_TYPE="LVCMOS33" */;

    IB Inst1_IB1 (.I(datain[1]), .O(buf_dataini1))
             /* synthesis IO_TYPE="LVCMOS33" */;

    IB Inst1_IB0 (.I(datain[0]), .O(buf_dataini0))
             /* synthesis IO_TYPE="LVCMOS33" */;

    assign sclk = clkin;
    assign dataini_t2 = buf_dataini2;
    assign dataini_t1 = buf_dataini1;
    assign dataini_t0 = buf_dataini0;


    // exemplar begin
    // exemplar attribute Inst3_IB IO_TYPE LVCMOS33
    // exemplar attribute Inst1_IB2 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_IB1 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_IB0 IO_TYPE LVCMOS33
    // exemplar end

endmodule
