/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.8 */
/* Wed Feb 25 23:53:50 2026 */

/* parameterized module instance */
aes50_rmii_rxd __ (.clkin( ), .reset( ), .sclk( ), .datain( ), .q( ));
