/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.8 */
/* C:\Programme2\Lattice\Diamond\ispfpga\bin\nt64\scuba.exe -w -n aes50_rmii_txd -lang verilog -synth synplify -bus_exp 7 -bb -arch sa5p00 -type iol -mode Transmit -io_type LVCMOS33 -width 3 -freq_in 50 -aligned -del -1 -gear 1 -fdc O:/fpga/lattice/pll/aes50_rmii_txd/aes50_rmii_txd.fdc  */
/* Mon Feb 23 10:33:18 2026 */


`timescale 1 ns / 1 ps
module aes50_rmii_txd (clkout, refclk, reset, data, dout)/* synthesis NGD_DRC_MASK=1 */;
    input wire refclk;
    input wire reset;
    input wire [2:0] data;
    output wire clkout;
    output wire [2:0] dout;

    wire scuba_vlo;
    wire scuba_vhi;
    wire buf_clkout;
    wire buf_douto2;
    wire buf_douto1;
    wire buf_douto0;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    ODDRX1F Inst4_ODDRX1F (.SCLK(refclk), .RST(reset), .D0(scuba_vhi), .D1(scuba_vlo), 
        .Q(buf_clkout));

    OFS1P3DX Inst3_OFS1P3DX2 (.D(data[2]), .SP(scuba_vhi), .SCLK(refclk), 
        .CD(reset), .Q(buf_douto2));

    OFS1P3DX Inst3_OFS1P3DX1 (.D(data[1]), .SP(scuba_vhi), .SCLK(refclk), 
        .CD(reset), .Q(buf_douto1));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    OFS1P3DX Inst3_OFS1P3DX0 (.D(data[0]), .SP(scuba_vhi), .SCLK(refclk), 
        .CD(reset), .Q(buf_douto0));

    OB Inst2_OB (.I(buf_clkout), .O(clkout))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB2 (.I(buf_douto2), .O(dout[2]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB1 (.I(buf_douto1), .O(dout[1]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB0 (.I(buf_douto0), .O(dout[0]))
             /* synthesis IO_TYPE="LVCMOS33" */;



    // exemplar begin
    // exemplar attribute Inst2_OB IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB2 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB1 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB0 IO_TYPE LVCMOS33
    // exemplar end

endmodule
