/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Sun Jan 04 22:54:31 2026 */

/* parameterized module instance */
lattice_pll_audio __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ));
