#define DSP_SETTINGS_VOLUME				0
#define DSP_SETTINGS_MATRIX_VOLUME 		2
#define DSP_SETTINGS_MAIN_VOLUME 		3
#define DSP_SETTINGS_MONITORING_VOLUME 	4
#define DSP_SETTINGS_SOLO			 	10
#define DSP_SETTINGS_MATRIX_SOLO		12
#define DSP_SETTINGS_MAIN_SOLO			13
