SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR arm)

SET(CROSS_COMPILE_PREFIX /opt/cross/bin/arm-openwrt-linux-muslgnueabi-)

SET(CMAKE_C_COMPILER   ${CROSS_COMPILE_PREFIX}gcc)
SET(CMAKE_CXX_COMPILER ${CROSS_COMPILE_PREFIX}g++)

#SET(CMAKE_SYSROOT ${CROSS_COMPILE_PREFIX})
SET(CMAKE_SYSROOT /opt/cross/arm-openwrt-linux-muslgnueabi)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
