/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Tue Feb 24 08:35:36 2026 */

/* parameterized module instance */
lattice_pll_phy __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ));
